### ISSUE TITLE
Our first event: January 26th 2016

### ISSUE THREAD

**Issue by jedireza** [connected-devices/sanfrancisco#3]
Mozilla SF is hosting us on January 26th from 6pm - 9pm. The address is: 2 Harrison St, San Francisco, CA 94105

Our first event will be like an open house.

 - 6:00pm - Meet everyone and mingle
 - 6:30pm - Show and tell
    - Introduction
    - Community presentations: What are you working on? Show the group in a 5-10 minute talk.
    - Talks and/or demos of some Mozilla Connected Devices projects.
 - 7:30pm - Discussion about how these meetups best serve the community.
    - Would we like presentation/mixer style events? Hacking/workshop days? A mix of the two?

We're still looking for community speakers. If you'd like to present something, show off a hack, mention a related meetup or have an idea for a workshop... comment to get involved or ask questions.

Attendees may register here: https://ti.to/connected-devices-sf/january-26th-2016

**Comment by moonrockfamily** [comment]
https://ti.to/connected-devices-sf/january-23rd-2016 is not found...

My interest stems from and the connected devices theme and your philosophy:
 - Write code in a simple and consistent way
 - It's just JavaScript
 - 100% test coverage

**Comment by jedireza** [comment]
@moonrockfamily thanks. I must have forgot to update this post. Our meeting has moved to the 26th instead. :+1:
