### ISSUE TITLE
Suggest you point to the Mozilla Community Participation guidelines instead

### ISSUE THREAD

**Issue by davidascher** [connected-devices/sanfrancisco#5]
+1 for having a CoC.

Given that Mozilla already has community participation guidelines which govern how we expect people to interact as part of the community, I suggest you point to that document rather than to the contributor covenant.  It has the advantage of having been discussed and "negotiated" with the Mozilla community already: 

It's at: https://www.mozilla.org/en-US/about/governance/policies/participation/

**Comment by jedireza** [comment]
Thanks for creating an issue and bringing this up.

My initial idea for the Connected Devices GitHub org is akin to how [NodeSchool](https://github.com/nodeschool/) is setup. Each city/region has it's own repo and is able to organize on their own and create their own CoC. Currently Lindsay and I are organizing the SF chapter, and we are both employed by Mozilla, but future organizers of this chapter (or other chapters) may not be.

With that in mind what are your thoughts?

**Comment by jedireza** [comment]
FYI: we're using the Moz participation guidelines now. 😉
